### Send request to localhost
POST http://localhost:3978/test-post HTTP/1.1
content-type: application/json

{
	"body":"Empty"
}

### Send request to App Service
POST https://<Your AppService Resource Name>.azurewebsites.net/test-post HTTP/1.1
content-Type: application/json

{
	"body":"Empty"
}


### Send request to App Service
POST http://192.168.0.20:8000 HTTP/1.1
content-Type: application/json

{
	"body":"Empty"
}

### flask
POST http://192.168.0.26:5000 HTTP/1.1
content-Type: application/json

{
	"body":"Empty"
}
